language: objective-c
osx_image: xcode8
xcode_workspace: ServerClient.xcworkspace
xcode_scheme: ServerClient

before_install:
- pod repo update


env:
  -EARLY_START_SIMULATOR=1


after_success:
  - bash <(curl -s https://codecov.io/bash)
