language: objective-c
osx_image: xcode8
xcode_workspace: ServerClient.xcworkspace # path to your xcodeproj folder
xcode_scheme: ServerClient


env:
  -EARLY_START_SIMULATOR=1 # early starting simulator reduces false negatives due to test timeouts


after_success:
  - bash <(curl -s https://codecov.io/bash)
